# Generated by Django 4.0.4 on 2022-05-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ngo_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngo_name', models.CharField(max_length=30)),
                ('owner_name', models.CharField(max_length=30)),
                ('Contact_no', models.IntegerField()),
                ('area_head', models.CharField(default='null', max_length=30)),
                ('areas', models.CharField(default='null', max_length=200)),
                ('Email', models.EmailField(max_length=254)),
                ('Password', models.CharField(max_length=30)),
                ('authorized', models.BooleanField()),
                ('pp_img', models.URLField(default='null')),
            ],
        ),
    ]
