# Generated by Django 4.0.4 on 2022-05-22 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo_profile',
            name='authorized',
            field=models.BooleanField(default=0),
        ),
    ]
