# Generated by Django 4.0.4 on 2022-05-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0003_remove_ngo_profile_pp_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30)),
                ('sdate', models.DateField()),
                ('edate', models.DateField()),
                ('narea', models.CharField(default='null', max_length=30)),
                ('nslot', models.CharField(default='null', max_length=30)),
                ('vneeded', models.IntegerField()),
                ('info', models.TextField()),
            ],
        ),
    ]
