# Generated by Django 4.0.4 on 2022-05-22 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ngo', '0004_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
