# Generated by Django 4.0.4 on 2022-05-17 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_profile_address_profile_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='vsession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vdate', models.DateField()),
            ],
        ),
    ]
