# Generated by Django 4.0.4 on 2022-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_vsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsession',
            name='varea',
            field=models.CharField(default='null', max_length=30),
        ),
        migrations.AddField(
            model_name='vsession',
            name='vslot',
            field=models.CharField(default='null', max_length=30),
        ),
    ]
