# Generated by Django 4.0.4 on 2022-05-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_vsession_varea_vsession_vslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsession',
            name='Email',
            field=models.EmailField(default='null', max_length=254),
        ),
    ]
