# Generated by Django 4.0.4 on 2022-05-19 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_vsession_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='pp_img',
            field=models.URLField(default='null'),
        ),
    ]
