# Generated by Django 4.0.4 on 2022-05-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_profile_pp_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pp_img',
            field=models.URLField(blank=True, default='null'),
        ),
    ]
