# Generated by Django 4.0.4 on 2022-05-23 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_profile_pp_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vsession',
            old_name='varea',
            new_name='vevent',
        ),
    ]
